query MemberDemosMetrics {
  memberDemosMetrics {
    storylineUuid
    storylineName
    uuid
    name
    started
    bounced
    avgScreenCompletion
    avgTimeSpent
    avgTimeSpentMilliseconds
    totalVisits
    uniqueVisitors
  }
}
