#import "../fragments/GuidesSettings.frag.gql"
query CompanySettings {
  companySettings {
    id
    mainColor
    secondaryColor
    disableLoader
    guidesSettings {
      ...GuidesSettings
    }
  }
}
