#import "./UserFields.frag.gql"

query {
  currentCompany {
    id
    name
    memberInvites {
      email
      role
    }
    members {
      id
      user {
        ...UserFields
      }
    }
  }
}
