query StorylineFlowsMetrics($storylineId: ID!) {
  storylineFlowsMetrics(storylineId: $storylineId) {
    flowName
    uniqueVisitors
    totalTimeSpent
    avgScreenCompletion
    avgTimeSpent
  }
}
