query StorylineMetrics($storylineId: ID!) {
  storylineMetrics(storylineId: $storylineId) {
    storylineUuid
    storylineName
    totalVisits
    uniqueVisitors
    totalTimeSpent
    avgScreenCompletion
    avgTimeSpent
  }
}
