use Mix.Config

config :api,
  env: "dev"

# Configure your database
config :api, Api.Repo,
  username: "postgres",
  password: "postgres",
  database: "api_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Configure your database
config :api, AsyncJobs.Repo,
  username: "postgres",
  password: "postgres",
  database: "jobs_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# LaunchDarkly SDK key
config :api, ld_sdk_key: "sdk-930972fd-6156-40d4-9335-dc2fbc64efa4"

config :workos,
  client_id: "client_01FEB2VKW3D49DT7W62K9EQNHP",
  api_key: "sk_test_a2V5XzAxRkZCMTIzOVFKNDdZVjJWSDJRSlc0OURTLEs4cnR5VWwwOFVtdTJpYWVTVWNVNnVZR3E",
  adapter: Tesla.Adapter.Mint

config :cors_plug,
  origin: [
    "https://demo.walnut.example.com:3001",
    "https://app.walnut.example.com:3000",
    "https://s3.*.amazonaws.com",
    ~r/chrome-extension:\/\/.*/
  ]

config :api,
  pubsub_server_conf: {Phoenix.PubSub, name: Api.PubSub}

config :api, :app_url, "https://app.walnut.example.com:3000"

config :api, :session, domain: "api.walnut.example.com"

config :api, :metabase,
  query_id_by_name: %{
    storyline_time_spent: 45,
    storyline_screen_completion: 12,
    storyline_demos_activity: 24,
    flows_time_spent: 14,
    flows_screen_completion: 15,
    demos_time_spent: 47,
    demos_screen_completion: 48
  },
  chart_id_by_name: %{
    demos_visits: 31
  }

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :api, ApiWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  url: [host: "api.walnut.example.com", scheme: "https"],
  code_reloader: true,
  reloadable_compilers: [:gettext, :phoenix, :elixir, :schema_sdl],
  check_origin: false,
  https: [
    port: 4001,
    cipher_suite: :strong,
    certfile: "../../../../../ssl/cert.crt",
    keyfile: "../../../../../ssl/key.pem",
    compress: true
  ],
  watchers: []

config :ex_aws,
  access_key_id: [{:awscli, "default", 30}],
  secret_access_key: [{:awscli, "default", 30}]

config :api, Api.Mailer, adapter: Bamboo.LocalAdapter

config :sentry,
  tags: %{
    env: "development"
  }

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger,
  backends: [:console]

config :logger, :console, metadata: :all

config :segment,
  write_key: "z3OVPMfQbzH9iuXKE3kF8QKI8XuKLPgs"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

import_config "dev.secret.exs"
