import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :api,
  env: "prod"

# LaunchDarkly SDK key
config :api, ld_sdk_key: "sdk-e4356325-edbe-4f0d-af47-f5180ebb0c2d"

config :api, ApiWeb.Endpoint,
  url: [host: "api.teamwalnut.com", port: 443, scheme: "https"],
  check_origin: [
    "https://www.walnutassets.com",
    "https://api.walnut.io",
    "https://app.walnut.io",
    "https://demo.walnut.io",
    "https://api.teamwalnut.com",
    "https://*.teamwalnut.com",
    "https://app.teamwalnut.com",
    "https://demo.teamwalnut.com",
    # allowing us to debug locally
    "https://app.walnut.example.com:3000",
    "https://*.netlify.app"
  ]

config :api, :session, domain: "api.teamwalnut.com"
config :api, :app_url, "https://app.teamwalnut.com"
config :api, :s3, bucket_name: "prod-walnut-assets-bucket"
config :api, :s3, artifact_bucket_name: "com.teamwalnut.artifacts."

config :api, :metabase,
  query_id_by_name: %{
    storyline_time_spent: 46,
    storyline_screen_completion: 35,
    storyline_demos_activity: 33,
    flows_time_spent: 37,
    flows_screen_completion: 34,
    demos_time_spent: 50,
    demos_screen_completion: 49
  },
  chart_id_by_name: %{
    demos_visits: 32
  }

config :workos,
  client_id: "client_01FEB2VKWHAS61BX4QFHNX0NW6",
  api_key: "sk_a2V5XzAxRkpDV1dRRUpBNkJGTkRBMkdISEgyQTMwLGtTeUVFckwzR0tBV3ljMlVXd01FY0thT0c",
  adapter: Tesla.Adapter.Mint

# Do not print debug messages in production
config :logger, level: :warn, compile_time_purge_level: :info

config :cors_plug,
  origin: [
    "https://www.walnutassets.com",
    "https://app.teamwalnut.com",
    "https://demo.teamwalnut.com",
    "https://app.walnut.io",
    "https://demo.walnut.io",
    # s3 assets loading
    "https://s3.*.amazonaws.com",
    # allowing us to debug locally
    "https://app.walnut.example.com:3000",
    "https://demo.walnut.example.com:3001",
    # subdomains
    ~r/https?:\/\/.*\.teamwalnut\.com$/,
    # PRs
    #  - App
    ~r/https?:\/\/.*--teamwalnut-app\.netlify\.app$/,
    #  - Demo
    ~r/https?:\/\/.*--teamwalnut-demo\.netlify\.app$/,
    # TODO, make sure we've the same hash in prod
    "chrome-extension://*"
  ]

config :sentry,
  tags: %{
    env: System.get_env("ENVIRONMENT"),
    environment: System.get_env("ENVIRONMENT")
  }

config :api, Api.Tracer,
  disabled?: false,
  env: System.get_env("ENVIRONMENT"),
  tags: [
    version: System.get_env("VERSION")
  ]

config :segment, write_key: "T2IS5wQPjG2b0qQ7zQeIAHB2qkHzavez"

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :api, ApiWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
#         transport_options: [socket_opts: [:inet6]]
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :api, ApiWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.
